// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkhldweiydvgnrroeehz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRraGxkd2VpeWR2Z25ycm9lZWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTMxNzksImV4cCI6MjA1OTA4OTE3OX0.7Ay2jw8CDS4svEH9yw9ssKSUBH_LLBDfgp804Wck2ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);